export default Object.freeze(  {

    ADD_POST:"ADD_POST",
    UPDATE_NEW_POST_TEXT:"UPDATE_NEW_POST_TEXT",
    ADD_MESSAGE:"ADD_MESSAGE",
    UPDATE_NEW_MESSAGE_TEXT:"UPDATE_NEW_MESSAGE_TEXT",
    FOLLOW:"FOLLOW",
    UNFOLLOW:"UNFOLLOW",
    SET_USERS: "SET_USERS",




})

